### ISSUE TITLE
issue with .techport() / api.py

### ISSUE THREAD

**Issue by rottedmood** [aschleg/nasapy#1]
Hi. In the version of nasapy that installs using pip3 install (0.2.6), the api.py has an error in it when calling the url variable for .techport(). 

The URL variable that is called is defined as " url = self.host + '/techport/api/projects/' ", but it shouldn't have the "/" at the end. I went in and edited the file to " url = self.host + '/techport/api/projects' " and it worked fine after.

**Comment by aschleg** [comment]
Thank you so much for pointing this out and providing a fix! I submitted a new version 0.2.7 to  PyPI that should resolve this. Will close the issue for now but please let me know if you continue to have any problems! Thanks again and apologies for the delay in my response!
